apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: techtrends
  name: techtrends
  namespace: sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techtrends
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: techtrends
    spec:
      containers:
      - image: awony/techtrends:latest
        name: techtrends
        resources: 
          limits:
            cpu:  "500m"
            memory: "128Mi"
          requests:
            cpu: "250m"
            memory: "64Mi"
        ports:
        - containerPort: 3111
        livenessProbe:
          httpGet:
             path: /healthz
             port: 3111
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3111
        imagePullPolicy: IfNotPresent
status: {}
